services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "3001:3001"
    secrets:
      - db-password
    env_file:
      - .env
    environment:
      - VITE_SERVER_URL=http://app:3001
      - NODE_ENV=production
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db-secrets/password.txt
