services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  app:
    container_name: app
    image: ghcr.io/nathangrenier/soen-343:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`soen343.ngrenier.com`)"
      - "traefik.http.services.app.loadbalancer.server.port=3001"
    ports:
      - "3001:3001"
    secrets:
      - db-password
    env_file:
      - .env
    environment:
      - VITE_SERVER_URL=http://app:3001
      - NODE_ENV=production
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    deploy:
      mode: replicated
      replicas: 3
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    container_name: postgres
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: db-secrets/password.txt
