name: Test
on:
  pull_request:
    branches:
      - "main"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Make install-all.sh executable
        run: chmod +x ./install-all.sh
      - name: Install dependencies
        run: ./install-all.sh
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.prod
          tags: ghcr.io/nathangrenier/soen-343:test
          push: false
